steps:
  - command: "echo 1; ls -lsa; sleep 3; touch hello"
    agents:
      hostname: "$BUILDKITE_AGENT_META_DATA_HOSTNAME"
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: "$PWD"
  - command: "echo 2; ls -lsa; sleep 3"
    agents:
      hostname: "$BUILDKITE_AGENT_META_DATA_HOSTNAME"
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: "$PWD"
